language: node_js
node_js:
  - '10'
dist: trusty
sudo: required
branches:
  only:
    - master
    - develop
install:
  - npm ci
cache:
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
before_script:
  - npm install -g firebase-tools
script:
  - ng lint
  - npm run test:headless
  - ng build --prod
  - npm run cy:verify
  - npm run ci:cy-run
deploy:
  - provider: script
    skip_cleanup: true
    script: firebase deploy --only hosting:production --token "<your-firebase-ci-token>"
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: firebase deploy --only hosting:development --token "<your-firebase-ci-token>"
    on:
      branch: develop
